// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

export function ChangeValue(v: config$0.ConfigType): $CancellablePromise<void> {
    return $Call.ByID(534687797, v);
}

export function GetValue(): $CancellablePromise<config$0.ConfigType> {
    return $Call.ByID(3966410473).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = config$0.ConfigType.createFrom;
