// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetLogDir 返回日志目录路径
 */
export function GetLogDir(): $CancellablePromise<string> {
    return $Call.ByID(3679700931);
}

/**
 * GetTodayLogs 获取今天的所有日志
 */
export function GetTodayLogs(logType: string, lines: number): $CancellablePromise<$models.LogEntry[]> {
    return $Call.ByID(2762079996, logType, lines).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListLogFiles 列出所有日志文件
 */
export function ListLogFiles(): $CancellablePromise<$models.LogFile[]> {
    return $Call.ByID(3914674027).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ReadLogFile 读取指定日志文件的内容
 */
export function ReadLogFile(filename: string, lines: number): $CancellablePromise<$models.LogEntry[]> {
    return $Call.ByID(3718881678, filename, lines).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.LogEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.LogFile.createFrom;
const $$createType3 = $Create.Array($$createType2);
