// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function CreateNode(name: string, token: string, address: string, serverIP: string, port: number): $CancellablePromise<models$0.Node | null> {
    return $Call.ByID(3039531582, name, token, address, serverIP, port).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetNodes(): $CancellablePromise<models$0.Node[]> {
    return $Call.ByID(12233975).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.Node.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
