// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DisableSOCKS5ForService 为指定网络服务禁用 SOCKS5 代理 (macOS)
 */
export function DisableSOCKS5ForService(service: string): $CancellablePromise<void> {
    return $Call.ByID(287244424, service);
}

/**
 * DisableSOCKS5Proxy 禁用 SOCKS5 系统代理 (macOS)
 */
export function DisableSOCKS5Proxy(): $CancellablePromise<void> {
    return $Call.ByID(2086950662);
}

/**
 * GetNetworkServices 获取所有网络服务 (macOS)
 */
export function GetNetworkServices(): $CancellablePromise<string[]> {
    return $Call.ByID(1327509692).then(($result: any) => {
        return $$createType0($result);
    });
}

export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(1480221581);
}

/**
 * SetSOCKS5ForService 为指定网络服务设置 SOCKS5 代理 (macOS)
 */
export function SetSOCKS5ForService(service: string, config: $models.ProxyConfig): $CancellablePromise<void> {
    return $Call.ByID(1626887488, service, config);
}

/**
 * SetSOCKS5Proxy 设置 SOCKS5 系统代理 (macOS)
 */
export function SetSOCKS5Proxy(config: $models.ProxyConfig): $CancellablePromise<void> {
    return $Call.ByID(4147263774, config);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(962235586);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3109470018);
}

export function SwitchNode(nodeId: number): $CancellablePromise<void> {
    return $Call.ByID(1938259646, nodeId);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
