// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * Create 创建用户
 */
export function Create(name: string, email: string): $CancellablePromise<models$0.User | null> {
    return $Call.ByID(2050164781, name, email).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Delete 删除用户
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(2615162234, id);
}

/**
 * GetAll 获取所有用户
 */
export function GetAll(): $CancellablePromise<models$0.User[]> {
    return $Call.ByID(236652226).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetByID 根据ID获取用户
 */
export function GetByID(id: number): $CancellablePromise<models$0.User | null> {
    return $Call.ByID(3129320063, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Update 更新用户
 */
export function Update(id: number, name: string, email: string): $CancellablePromise<models$0.User | null> {
    return $Call.ByID(314768740, id, name, email).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.User.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
