// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../../client/core/models.js";

export class ConfigType {
    "ListenAddr": string;
    "ListenPort": number;
    "DNSServer": string;
    "ECHDomain": string;
    "RoutingMode": core$0.RoutingMode;
    "SelectNodeId": number;

    /** Creates a new ConfigType instance. */
    constructor($$source: Partial<ConfigType> = {}) {
        if (!("ListenAddr" in $$source)) {
            this["ListenAddr"] = "";
        }
        if (!("ListenPort" in $$source)) {
            this["ListenPort"] = 0;
        }
        if (!("DNSServer" in $$source)) {
            this["DNSServer"] = "";
        }
        if (!("ECHDomain" in $$source)) {
            this["ECHDomain"] = "";
        }
        if (!("RoutingMode" in $$source)) {
            this["RoutingMode"] = core$0.RoutingMode.$zero;
        }
        if (!("SelectNodeId" in $$source)) {
            this["SelectNodeId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigType instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigType {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigType($$parsedSource as Partial<ConfigType>);
    }
}
