// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RoutingMode 路由模式常量
 */
export enum RoutingMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 全局代理
     */
    RoutingModeGlobal = "global",

    /**
     * 跳过中国大陆
     */
    RoutingModeBypassCN = "bypass_cn",

    /**
     * 直连模式
     */
    RoutingModeNone = "none",
};
